export {
  initCrypto,
  deriveKeyFromPassphrase,
  generateKey,
  generateNonce,
  encrypt,
  decrypt,
  encryptString,
  decryptString,
  encryptJSON,
  decryptJSON,
  encryptKey,
  decryptKey,
  generateKeyPair,
  encryptForRecipient,
  decryptFromSender,
  hash,
  hashString,
  secureWipe,
  toBase64,
  fromBase64,
  toHex,
  fromHex,
  randomBytes,
  secureCompare,
  generateSigningKeyPair,
  sign,
  verify,
  DEFAULT_KEY_DERIVATION_CONFIG,
  type KeyDerivationConfig,
} from './encryption.js';

export {
  KeyManager,
  createKeyManager,
  type MasterKeyData,
  type VaultKeyData,
  type DelegationKeyMetadata,
} from './keys.js';
