# .HMAN -- one-command Azure deployment (Phase 1).
#
# Provisions:
#   - Static Web Apps  (frontend)
#   - Azure Relay      (bridge tunnel)
#   - Key Vault        (bearer token)
#   - App Insights     (observability)
#
# Does NOT touch DNS or Front Door. Your frontend will live on the default
# *.azurestaticapps.net hostname; your bridge on <namespace>.servicebus.windows.net.
# Both public HTTPS, usable immediately.
#
# Phase 2 (separate Bicep, separate resource group) is infra/modules/frontdoor-routes.bicep --
# run it AFTER you've added the TXT validation records for hman.tailor.au /
# bridge.tailor.au at your DNS provider.
#
# Usage:
#   pwsh -File ops/azure-deploy.ps1 -ResourceGroup rg-hman-prod

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ResourceGroup,
    [string]$Location = 'australiaeast',
    [string]$MemberId = 'member',
    [switch]$SkipFrontendDeploy
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

function Info($msg)  { Write-Host "  >> $msg" -ForegroundColor Cyan }
function Ok($msg)    { Write-Host "  [ok] $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Warning $msg }

# -- 1. Ensure az login ---------------------------------------------

try {
    $account = az account show --only-show-errors 2>$null | ConvertFrom-Json
    if (-not $account) { throw "not logged in" }
    Info "Azure: $($account.name) ($($account.id))"
} catch {
    Info "Logging in to Azure..."
    az login --only-show-errors | Out-Null
    $account = az account show | ConvertFrom-Json
}

$memberObjectId = (az ad signed-in-user show --query id -o tsv).Trim()
if (-not $memberObjectId) { throw "Could not resolve signed-in-user object id." }
Info "Deploying as user objectId $memberObjectId"

# -- 2. Resource group ----------------------------------------------

Info "Ensuring resource group $ResourceGroup in $Location..."
az group create --name $ResourceGroup --location $Location --only-show-errors | Out-Null
Ok "Resource group ready."

# -- 3. Bicep what-if (preview) -------------------------------------

Info "Previewing changes (what-if)..."
$bicepParams = @(
    "projectName=hman"
    "environment=prod"
    "memberObjectId=$memberObjectId"
    "memberId=$MemberId"
)

$whatif = az deployment group what-if `
    --resource-group $ResourceGroup `
    --template-file "$repoRoot/infra/main.bicep" `
    --parameters $bicepParams `
    --only-show-errors `
    --no-pretty-print `
    -o tsv 2>&1
if ($LASTEXITCODE -ne 0) {
    Warn "what-if returned warnings (continuing): $whatif"
}

# -- 4. Bicep deploy ------------------------------------------------

$deploymentName = "hman-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
Info "Running Bicep deployment $deploymentName (this takes 2-4 minutes)..."

$deployRaw = az deployment group create `
    --resource-group $ResourceGroup `
    --name $deploymentName `
    --template-file "$repoRoot/infra/main.bicep" `
    --parameters $bicepParams `
    --only-show-errors `
    -o json

if ($LASTEXITCODE -ne 0) { throw "Bicep deployment failed." }

$deploy = $deployRaw | ConvertFrom-Json
$out = $deploy.properties.outputs
Ok "Bicep deployment succeeded."

$swaName        = $out.swaName.value
$swaHostname    = $out.swaDefaultHostname.value
$relayNs        = $out.relayNamespace.value
$relayFqdn      = $out.relayNamespaceFqdn.value
$relayHc        = $out.relayHybridConnection.value
$kvName         = $out.keyVaultName.value
$memberBridgeUrl = $out.memberBridgeUrl.value

Info "SWA:        $swaName"
Info "SWA host:   $swaHostname"
Info "Relay:      $relayNs / $relayHc"
Info "Relay FQDN: $relayFqdn"
Info "Key Vault:  $kvName"

# -- 5. Generate + store HMAN_AUTH_TOKEN ----------------------------

$token = -join ((1..48) | ForEach-Object { '{0:x}' -f (Get-Random -Maximum 16) })
Info "Generated HMAN_AUTH_TOKEN (48 hex chars). Storing in $kvName..."
az keyvault secret set --vault-name $kvName --name 'HMAN-AUTH-TOKEN' --value $token --only-show-errors | Out-Null
Ok "Token stored as secret HMAN-AUTH-TOKEN."

# -- 6. Fetch Relay listener key and write ~/.hman/bridge.env -------

Info "Fetching Relay listener key..."
$listenerKey = (az relay hyco authorization-rule keys list `
    --resource-group $ResourceGroup `
    --namespace-name $relayNs `
    --hybrid-connection-name $relayHc `
    --name 'listener' `
    --query primaryKey -o tsv).Trim()

$dataDir = Join-Path $env:USERPROFILE '.hman'
if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir | Out-Null }
$envFile = Join-Path $dataDir 'bridge.env'

$allowedOrigins = "https://$swaHostname,https://hman.tailor.au"

@"
# .HMAN bridge configuration -- generated by ops/azure-deploy.ps1
# Do not commit this file anywhere.
HMAN_AUTH_TOKEN=$token
HMAN_ALLOWED_ORIGINS=$allowedOrigins
HMAN_RELAY_NAMESPACE=$relayFqdn
HMAN_RELAY_PATH=$relayHc
HMAN_RELAY_KEYNAME=listener
HMAN_RELAY_KEY=$listenerKey
HMAN_LOCAL_BRIDGE_URL=http://127.0.0.1:8765
"@ | Out-File -FilePath $envFile -Encoding utf8
Ok "Wrote $envFile"

# -- 7. Web frontend deploy ----------------------------------------

if ($SkipFrontendDeploy) {
    Warn "Skipping frontend deploy (-SkipFrontendDeploy)."
} else {
    Info "Fetching SWA deployment token..."
    $swaToken = (az staticwebapp secrets list `
        --name $swaName `
        --resource-group $ResourceGroup `
        --query 'properties.apiKey' -o tsv).Trim()

    Info "Building web-dashboard with VITE_HMAN_BRIDGE=$memberBridgeUrl"
    Push-Location "$repoRoot/apps/web-dashboard"
    try {
        "VITE_HMAN_BRIDGE=$memberBridgeUrl" | Out-File -FilePath '.env.production' -Encoding utf8
        if (-not (Test-Path 'node_modules')) {
            npm install --silent
        }
        npm run build --silent
        if (-not (Get-Command swa -ErrorAction SilentlyContinue)) {
            npm install -g @azure/static-web-apps-cli --silent | Out-Null
        }
        swa deploy dist --deployment-token $swaToken --env production
    } finally {
        Pop-Location
    }
    Ok "Frontend deployed."
}

# -- 8. Summary ----------------------------------------------------

Write-Host ""
Write-Host "  ============================================================"
Write-Host "  .HMAN Azure Phase 1 deployment complete." -ForegroundColor Green
Write-Host "  ============================================================"
Write-Host ""
Write-Host "  Frontend:      https://$swaHostname"
Write-Host "  Bridge URL:    $memberBridgeUrl"
Write-Host "  Key Vault:     $kvName"
Write-Host "  RG in Azure:   https://portal.azure.com/#@/resource/subscriptions/$($account.id)/resourceGroups/$ResourceGroup"
Write-Host ""
Write-Host "  The bearer token is in $envFile (and in Key Vault)." -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Install the relay listener as a Windows auto-start (Admin PowerShell):"
Write-Host "         pwsh -File ops/install-windows-service.ps1 -Tunnel azure"
Write-Host "    2. Open https://$swaHostname -- paste the auth token when prompted."
Write-Host "    3. (Later) Phase 2: run infra/modules/frontdoor-routes.bicep to"
Write-Host "       attach hman.tailor.au / bridge.tailor.au via your Front Door."
Write-Host ""
