# .HMAN — one-command Azure deployment.
#
# What it does:
#   1. az login (if not already logged in)
#   2. Creates the resource group if missing
#   3. Runs Bicep to provision SWA + Relay + Key Vault + App Insights + DNS records
#   4. Generates and stores HMAN_AUTH_TOKEN in Key Vault
#   5. Writes ~/.hman/bridge.env with the Relay listener configuration
#   6. Deploys the web dashboard to Static Web Apps
#
# Usage:
#   pwsh -File ops/azure-deploy.ps1 `
#     -ResourceGroup rg-hman-prod `
#     -WebDomain hman.tailor.au `
#     -BridgeDomain bridge.tailor.au `
#     -DnsZone tailor.au

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ResourceGroup,
    [Parameter(Mandatory = $true)][string]$WebDomain,
    [Parameter(Mandatory = $true)][string]$BridgeDomain,
    [Parameter(Mandatory = $true)][string]$DnsZone,

    [string]$Location = 'australiaeast',
    [string]$MemberId = 'member',
    [switch]$CreateDnsZone,
    [switch]$SkipFrontendDeploy
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

function Info($msg)  { Write-Host "  → $msg" -ForegroundColor Cyan }
function Ok($msg)    { Write-Host "  ✓ $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Warning $msg }

# ── 1. Ensure az login ─────────────────────────────────────────────

try {
    $account = az account show --only-show-errors 2>$null | ConvertFrom-Json
    if (-not $account) { throw "not logged in" }
    Info "Azure: $($account.name) ($($account.id))"
} catch {
    Info "Logging in to Azure…"
    az login --only-show-errors | Out-Null
    $account = az account show | ConvertFrom-Json
}

$memberObjectId = (az ad signed-in-user show --query id -o tsv).Trim()
if (-not $memberObjectId) { throw "Could not resolve signed-in-user object id." }
Info "Deploying as user objectId $memberObjectId"

# ── 2. Resource group ──────────────────────────────────────────────

Info "Ensuring resource group $ResourceGroup in $Location…"
az group create --name $ResourceGroup --location $Location --only-show-errors | Out-Null
Ok "Resource group ready."

# ── 3. Bicep deploy ────────────────────────────────────────────────

$deploymentName = "hman-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
Info "Running Bicep deployment $deploymentName (this takes 2-3 minutes)…"

$bicepParams = @(
    "projectName=hman"
    "environment=prod"
    "webCustomDomain=$WebDomain"
    "bridgeCustomDomain=$BridgeDomain"
    "dnsZoneName=$DnsZone"
    "createDnsZone=$($CreateDnsZone.IsPresent.ToString().ToLower())"
    "memberObjectId=$memberObjectId"
    "memberId=$MemberId"
)

$deployRaw = az deployment group create `
    --resource-group $ResourceGroup `
    --name $deploymentName `
    --template-file "$repoRoot/infra/main.bicep" `
    --parameters $bicepParams `
    --only-show-errors `
    -o json

if ($LASTEXITCODE -ne 0) { throw "Bicep deployment failed." }

$deploy = $deployRaw | ConvertFrom-Json
$out = $deploy.properties.outputs
Ok "Bicep deployment succeeded."

$swaName = $out.swaName.value
$relayNs = $out.relayNamespace.value
$relayHc = $out.relayHybridConnection.value
$kvName = $out.keyVaultName.value
Info "SWA:        $swaName"
Info "Relay:      $relayNs / $relayHc"
Info "Key Vault:  $kvName"

# ── 4. Generate + store HMAN_AUTH_TOKEN ────────────────────────────

$token = -join ((1..48) | ForEach-Object { '{0:x}' -f (Get-Random -Maximum 16) })
Info "Generated HMAN_AUTH_TOKEN (48 hex chars). Storing in $kvName…"
az keyvault secret set --vault-name $kvName --name 'HMAN-AUTH-TOKEN' --value $token --only-show-errors | Out-Null
Ok "Token stored as secret HMAN-AUTH-TOKEN."

# ── 5. Fetch Relay listener key and write ~/.hman/bridge.env ───────

Info "Fetching Relay listener key…"
$listenerKey = (az relay hyco authorization-rule keys list `
    --resource-group $ResourceGroup `
    --namespace-name $relayNs `
    --hybrid-connection-name $relayHc `
    --name 'listener' `
    --query primaryKey -o tsv).Trim()

$dataDir = Join-Path $env:USERPROFILE '.hman'
if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir | Out-Null }
$envFile = Join-Path $dataDir 'bridge.env'

@"
# .HMAN bridge configuration — generated by ops/azure-deploy.ps1
# Do not commit this file anywhere.
HMAN_AUTH_TOKEN=$token
HMAN_ALLOWED_ORIGINS=https://$WebDomain
HMAN_RELAY_NAMESPACE=$relayNs.servicebus.windows.net
HMAN_RELAY_PATH=$relayHc
HMAN_RELAY_KEYNAME=listener
HMAN_RELAY_KEY=$listenerKey
HMAN_LOCAL_BRIDGE_URL=http://127.0.0.1:8765
"@ | Out-File -FilePath $envFile -Encoding utf8
Ok "Wrote $envFile"

# ── 6. Web frontend deploy ────────────────────────────────────────

if ($SkipFrontendDeploy) {
    Warn "Skipping frontend deploy (you passed -SkipFrontendDeploy)."
} else {
    Info "Fetching SWA deployment token…"
    $swaToken = (az staticwebapp secrets list `
        --name $swaName `
        --resource-group $ResourceGroup `
        --query 'properties.apiKey' -o tsv).Trim()

    Info "Building web-dashboard with VITE_HMAN_BRIDGE=https://$BridgeDomain"
    Push-Location "$repoRoot/apps/web-dashboard"
    try {
        "VITE_HMAN_BRIDGE=https://$BridgeDomain" | Out-File -FilePath '.env.production' -Encoding utf8
        if (-not (Test-Path 'node_modules')) {
            npm install --silent
        }
        npm run build --silent
        if (-not (Get-Command swa -ErrorAction SilentlyContinue)) {
            npm install -g @azure/static-web-apps-cli --silent | Out-Null
        }
        swa deploy dist --deployment-token $swaToken --env production
    } finally {
        Pop-Location
    }
    Ok "Frontend deployed."
}

Write-Host ""
Write-Host "  ════════════════════════════════════════════════════════════"
Write-Host "  .HMAN Azure deployment complete." -ForegroundColor Green
Write-Host "  ════════════════════════════════════════════════════════════"
Write-Host ""
Write-Host "  Web:           https://$WebDomain"
Write-Host "  Bridge:        https://$BridgeDomain"
Write-Host "  Token vault:   https://portal.azure.com/#@/resource/subscriptions/$($account.id)/resourceGroups/$ResourceGroup/providers/Microsoft.KeyVault/vaults/$kvName"
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Configure your DNS provider with the records in $PSCommandPath output"
Write-Host "    2. Install the relay listener as a Windows service:"
Write-Host "         pwsh -File ops/install-windows-service.ps1 -Tunnel azure"
Write-Host "    3. Open https://$WebDomain — paste the auth token when prompted."
Write-Host ""
